#!/usr/bin/sh

clear
export WAYLAND_DEBUG=1

#
# Generate xdg-shell-client.h and .c
#
wayland-scanner \
    client-header \
    modules/wayland-protocols/stable/xdg-shell/xdg-shell.xml \
    xdg/xdg-shell-client.h

wayland-scanner \
    public-code \
    modules/wayland-protocols/stable/xdg-shell/xdg-shell.xml \
    xdg/xdg-shell-client.c

#
# Generate wayland-client.h and .c
#
wayland-scanner \
    client-header \
    modules/wayland/protocol/wayland.xml \
    wayland/wayland-client.h

wayland-scanner \
    public-code \
    modules/wayland/protocol/wayland.xml \
    wayland/wayland-client.c

#
# Compile
#
gcc \
    -g \
    main.c \
    xdg/*.c \
    playland/*.c \
    -o \
    bin/main \
    -lwayland-client;

#
# Run
#
./bin/main
