#!/usr/bin/python3

WIDTH=2560
HEIGHT=1440
GOOGLE_BLUE=[0xf4, 0x85, 0x42, 255]

bgra = []

for w in range(WIDTH):
    for h in range(HEIGHT):
                #0    0    0    a
        bgra += GOOGLE_BLUE

buffer = b''.join([byte.to_bytes(1, byteorder='little') for byte in bgra])

with open('./bin/pool.bin', 'wb') as bufferFile:
    bufferFile.write(buffer)
